from __future__ import annotations

from typing import Any


def get_roc114_summary_similarity_quality() -> dict[str, Any]:
    return {
        "report_title": "ROC 114 摘要與相似案件品質檢查",
        "report_date": "2026-07-07",
        "method_version": "rule_based_v1",
        "scope": {
            "roc_year": 114,
            "case_count": 2500,
            "dispute_type_count": 41,
            "formal_database_case_count": 2992,
            "formal_database_year_distribution": {
                "ROC 114": 2500,
                "ROC 115": 492,
            },
        },
        "top_dispute_types": [
            {"name": "必要性醫療", "count": 786},
            {"name": "理賠金額認定", "count": 203},
            {"name": "手術認定", "count": 183},
            {"name": "承保範圍", "count": 174},
            {"name": "投保時已患疾病或在妊娠中", "count": 170},
            {"name": "業務招攬爭議", "count": 148},
            {"name": "事故發生原因認定", "count": 114},
            {"name": "除外責任", "count": 101},
            {"name": "失能或豁免保費體況認定", "count": 72},
            {"name": "違反告知義務", "count": 66},
        ],
        "summary_field_stats": [
            {
                "field": "holding",
                "non_empty": 2500,
                "min_length": 17,
                "median_length": 22.0,
                "average_length": 27.2,
                "max_length": 297,
            },
            {
                "field": "applicant_claim",
                "non_empty": 2500,
                "min_length": 141,
                "median_length": 511.0,
                "average_length": 575.4,
                "max_length": 1203,
            },
            {
                "field": "reasoning",
                "non_empty": 2500,
                "min_length": 36,
                "median_length": 1602.0,
                "average_length": 1419.2,
                "max_length": 1603,
            },
        ],
        "contamination_checks": [
            {"name": "applicant_claim 吃到「三、相對人」標題", "issue_count": 0},
            {"name": "reasoning 吃到「七、綜上」或「八、據上」標題", "issue_count": 0},
            {"name": "三個摘要欄位全部為空", "issue_count": 0},
        ],
        "scoring_rules": [
            {
                "name": "相同爭議類型",
                "points": 60,
                "description": "優先確認案件是否屬於同一爭議分類，這是目前規則式相似度最主要的依據。",
            },
            {
                "name": "相同評議結果",
                "points": 15,
                "description": "若評議結果一致，代表案件處理方向可能較接近。",
            },
            {
                "name": "相同決定類別",
                "points": 5,
                "description": "目前資料以評議決定書為主，此項用來保留跨文件類型擴充空間。",
            },
            {
                "name": "摘要關鍵詞重疊",
                "points": 30,
                "description": "每個保險領域關鍵詞加 6 分，最高 30 分，用來補足同類型內的主題接近程度。",
            },
        ],
        "sample_cases": [
            {
                "case_number": "114年評字第002132號",
                "dispute_type": "必要性醫療",
                "decision_date": "114.06.13",
                "holding_length": 22,
                "applicant_claim_length": 908,
                "reasoning_length": 1255,
                "top5_same_dispute_type_count": 5,
            },
            {
                "case_number": "114年評字第001627號",
                "dispute_type": "理賠金額認定",
                "decision_date": "114.06.13",
                "holding_length": 22,
                "applicant_claim_length": 324,
                "reasoning_length": 1523,
                "top5_same_dispute_type_count": 5,
            },
            {
                "case_number": "114年評字第002828號",
                "dispute_type": "手術認定",
                "decision_date": "114.08.08",
                "holding_length": 22,
                "applicant_claim_length": 1104,
                "reasoning_length": 1603,
                "top5_same_dispute_type_count": 5,
            },
            {
                "case_number": "114年評字第002850號",
                "dispute_type": "承保範圍",
                "decision_date": "114.07.25",
                "holding_length": 22,
                "applicant_claim_length": 400,
                "reasoning_length": 776,
                "top5_same_dispute_type_count": 5,
            },
            {
                "case_number": "114年評字第002312號",
                "dispute_type": "投保時已患疾病或在妊娠中",
                "decision_date": "114.07.11",
                "holding_length": 22,
                "applicant_claim_length": 949,
                "reasoning_length": 1603,
                "top5_same_dispute_type_count": 5,
            },
            {
                "case_number": "114年評字第002430號",
                "dispute_type": "業務招攬爭議",
                "decision_date": "114.08.22",
                "holding_length": 22,
                "applicant_claim_length": 779,
                "reasoning_length": 1603,
                "top5_same_dispute_type_count": 5,
            },
            {
                "case_number": "114年評字第001685號",
                "dispute_type": "事故發生原因認定",
                "decision_date": "114.06.13",
                "holding_length": 22,
                "applicant_claim_length": 409,
                "reasoning_length": 1603,
                "top5_same_dispute_type_count": 5,
            },
            {
                "case_number": "114年評字第002232號",
                "dispute_type": "除外責任",
                "decision_date": "114.07.25",
                "holding_length": 22,
                "applicant_claim_length": 260,
                "reasoning_length": 1603,
                "top5_same_dispute_type_count": 5,
            },
            {
                "case_number": "114年評字第001235號",
                "dispute_type": "失能或豁免保費體況認定",
                "decision_date": "114.05.09",
                "holding_length": 22,
                "applicant_claim_length": 408,
                "reasoning_length": 773,
                "top5_same_dispute_type_count": 5,
            },
            {
                "case_number": "114年評字第002265號",
                "dispute_type": "違反告知義務",
                "decision_date": "114.07.11",
                "holding_length": 22,
                "applicant_claim_length": 524,
                "reasoning_length": 1011,
                "top5_same_dispute_type_count": 5,
            },
        ],
        "similar_stats": {
            "evaluated_cases": 2500,
            "top1_same_dispute_type": 2498,
            "top1_same_dispute_type_rate": 99.92,
            "top5_contains_same_dispute_type": 2498,
            "top5_contains_same_dispute_type_rate": 99.92,
            "average_same_type_count_in_top5": 4.98,
            "min_same_type_count_in_top5": 0,
        },
        "known_exceptions": [
            {
                "case_number": "114年評字第000035號",
                "dispute_type": "挪用保費",
                "decision_date": "114.04.11",
                "reason": "全部 2992 筆中此爭議類型只有 1 筆，無同類型候選案件。",
            },
            {
                "case_number": "114年評字第003057號",
                "dispute_type": "未到期保費之返還",
                "decision_date": "114.08.22",
                "reason": "全部 2992 筆中此爭議類型只有 1 筆，無同類型候選案件。",
            },
        ],
        "conclusions": [
            {
                "title": "摘要品質可接受",
                "items": [
                    "摘要三欄覆蓋率為 2500 / 2500。",
                    "沒有偵測到明顯截段污染。",
                    "前十大爭議類型抽樣摘要可回溯到原文段落。",
                ],
            },
            {
                "title": "相似案件 baseline 可展示",
                "items": [
                    "Top 1 同爭議類型率為 99.92%。",
                    "Top 5 包含同爭議類型率為 99.92%。",
                    "前十大爭議類型抽樣案件 Top 5 皆為同爭議類型。",
                ],
            },
        ],
        "limitations": [
            "規則式相似案件偏向同爭議類型排序，尚不等同語意相似或法律推理相似。",
            "稀有爭議類型若只有 1 筆，無法產生同類型相似案件。",
            "reasoning 是從原文抽取長段落，不是濃縮摘要。",
        ],
        "next_steps": [
            "在前端相似案件區塊加入低信心提示。",
            "導入 embedding 前，先建立 chunking 設計。",
            "展示時明確說明目前為可解釋規則式版本。",
        ],
    }
